name: Build Android NDLLs

on:
  workflow_dispatch:

jobs:
  build-Android:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup Haxe
      uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.3.6
        
    - name: Install Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: "25.1.8937393"  # 使用较新的NDK版本
        
    - name: Install dependencies
      run: |
        brew install pkg-config
        
        # 安装 Haxe 库
        haxelib install hxcpp
        haxelib install lime
        haxelib run lime setup
        haxelib git linc_luajit https://github.com/NovaFlare-Engine-Concentration/linc_luajit-rewriten.git main
        
    - name: Configure environment
      run: |
        # 设置NDK环境变量
        echo "NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "HXCPP=/Users/runner/haxe/lib/hxcpp/git/bin" >> $GITHUB_ENV
        
        # 创建必要的符号链接
        mkdir -p project/include
        cd project/include
        ln -s $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1 c++ || true
        
    - name: Build NDLLs
      run: |
        cd project
        
        # 设置编译标志
        export COMMON_FLAGS="-Iinclude -Iinclude/c++ -DLUAJIT_ENABLE_LUA52COMPAT"
        
        # 为所有架构构建
        for arch in armeabi-v7a arm64-v8a x86 x86_64; do
          case $arch in
            armeabi-v7a) flags="-DHXCPP_ARMV7" ;;
            arm64-v8a) flags="-DHXCPP_ARM64" ;;
            x86) flags="-DHXCPP_X86" ;;
            x86_64) flags="-DHXCPP_X86_64" ;;
          esac
          
          echo "Building $arch..."
          haxelib run hxcpp Build.xml -Dandroid $flags $COMMON_FLAGS
        done
        
    - name: Verify artifacts
      run: |
        ls -la project/luajit/lib/
        echo "Artifacts:"
        find project/ndll -name '*.ndll' -o -name '*.a'
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ndll-binaries
        path: project/luajit/lib/
        if-no-files-found: error
